PUT_OPERATION = 1
GET_OPERATION = 2
DEL_OPERATION = 3
WAL_FILE_NAME_FORMAT = "{}.wal"
WAL_HEADER_FORMAT = "<IHI"
CRC_FORMAT = "<I"
TOMBSTONE_ENTRY = "TOMBSTONE"
WAL_HEADER_SIZE = 10
FILE_START_INDEX = 0
CRC_SIZE = 4
WHENCE_BEGINING = 0

IDX_FILE_NAME_FORMAT = "{}.idx"
IDX_HEADER_FORMAT = WAL_HEADER_FORMAT
IDX_HEADER_SIZE = WAL_HEADER_SIZE

SST_FILE_NAME_FORMAT = "{}.sst"
SST_HEADER_FORMAT = WAL_HEADER_FORMAT
SST_HEADER_SIZE = WAL_HEADER_SIZE
